<?php

namespace Database\Seeders;

use App\Models\Bank as ModelsBank;
use Illuminate\Database\Seeder;

class Bank extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        $banks = [
            ['code' => '001', 'label' => '001 - BANCO DO BRASIL S/A'],
            ['code' => '002', 'label' => '002 - BANCO CENTRAL DO BRASIL'],
            ['code' => '003', 'label' => '003 - BANCO DA AMAZONIA S.A'],
            ['code' => '004', 'label' => '004 - BANCO DO NORDESTE DO BRASIL S.A'],
            ['code' => '007', 'label' => '007 - BANCO NAC DESENV. ECO. SOCIAL S.A'],
            ['code' => '008', 'label' => '008 - BANCO MERIDIONAL DO BRASIL'],
            ['code' => '020', 'label' => '020 - BANCO DO ESTADO DE ALAGOAS S.A'],
            ['code' => '021', 'label' => '021 - BANCO DO ESTADO DO ESPIRITO SANTO S.A'],
            ['code' => '022', 'label' => '022 - BANCO DE CREDITO REAL DE MINAS GERAIS SA'],
            ['code' => '024', 'label' => '024 - BANCO DO ESTADO DE PERNAMBUCO'],
            ['code' => '025', 'label' => '025 - BANCO ALFA S/A'],
            ['code' => '026', 'label' => '026 - BANCO DO ESTADO DO ACRE S.A'],
            ['code' => '027', 'label' => '027 - BANCO DO ESTADO DE SANTA CATARINA S.A'],
            ['code' => '028', 'label' => '028 - BANCO DO ESTADO DA BAHIA S.A'],
            ['code' => '029', 'label' => '029 - BANCO DO ESTADO DO RIO DE JANEIRO S.A'],
            ['code' => '030', 'label' => '030 - BANCO DO ESTADO DA PARAIBA S.A'],
            ['code' => '031', 'label' => '031 - BANCO DO ESTADO DE GOIAS S.A'],
            ['code' => '032', 'label' => '032 - BANCO DO ESTADO DO MATO GROSSO S.A.'],
            ['code' => '033', 'label' => '033 - BANCO DO ESTADO DE SAO PAULO S.A'],
            ['code' => '034', 'label' => '034 - BANCO DO ESADO DO AMAZONAS S.A'],
            ['code' => '035', 'label' => '035 - BANCO DO ESTADO DO CEARA S.A'],
            ['code' => '036', 'label' => '036 - BANCO DO ESTADO DO MARANHAO S.A'],
            ['code' => '037', 'label' => '037 - BANCO DO ESTADO DO PARA S.A'],
            ['code' => '038', 'label' => '038 - BANCO DO ESTADO DO PARANA S.A'],
            ['code' => '039', 'label' => '039 - BANCO DO ESTADO DO PIAUI S.A'],
            ['code' => '041', 'label' => '041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A'],
            ['code' => '047', 'label' => '047 - BANCO DO ESTADO DE SERGIPE S.A'],
            ['code' => '048', 'label' => '048 - BANCO DO ESTADO DE MINAS GERAIS S.A'],
            ['code' => '059', 'label' => '059 - BANCO DO ESTADO DE RONDONIA S.A'],
            ['code' => '066', 'label' => '066 - BANCO MORGAN STANLEY S.A'],
            ['code' => '070', 'label' => '070 - BANCO DE BRASILIA S.A'],
            ['code' => '077', 'label' => '077 - BANCO DE INTER S.A'],
            ['code' => '104', 'label' => '104 - CAIXA ECONOMICA FEDERAL'],
            ['code' => '106', 'label' => '106 - BANCO ITABANCO S.A.'],
            ['code' => '107', 'label' => '107 - BANCO BBM S.A'],
            ['code' => '109', 'label' => '109 - BANCO CREDIBANCO S.A'],
            ['code' => '116', 'label' => '116 - BANCO B.N.L DO BRASIL S.A'],
            ['code' => '129', 'label' => '129 - UBS BRASIL BANCO DE INVESTIMENTO S.A.'],
            ['code' => '148', 'label' => '148 - MULTI BANCO S.A'],
            ['code' => '151', 'label' => '151 - CAIXA ECONOMICA DO ESTADO DE SAO PAULO'],
            ['code' => '153', 'label' => '153 - CAIXA ECONOMICA DO ESTADO DO R.G.SUL'],
            ['code' => '165', 'label' => '165 - BANCO NORCHEM S.A'],
            ['code' => '166', 'label' => '166 - BANCO INTER-ATLANTICO S.A'],
            ['code' => '168', 'label' => '168 - BANCO C.C.F. BRASIL S.A'],
            ['code' => '175', 'label' => '175 - CONTINENTAL BANCO S.A'],
            ['code' => '184', 'label' => '184 - BBA - CREDITANSTALT S.A'],
            ['code' => '199', 'label' => '199 - BANCO FINANCIAL PORTUGUES'],
            ['code' => '200', 'label' => '200 - BANCO FRICRISA AXELRUD S.A'],
            ['code' => '201', 'label' => '201 - BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A'],
            ['code' => '204', 'label' => '204 - BANCO S.R.L S.A'],
            ['code' => '205', 'label' => '205 - BANCO SUL AMERICA S.A'],
            ['code' => '206', 'label' => '206 - BANCO MARTINELLI S.A'],
            ['code' => '208', 'label' => '208 - BANCO PACTUAL S.A'],
            ['code' => '210', 'label' => '210 - DEUTSCH SUDAMERIKANICHE BANK AG'],
            ['code' => '211', 'label' => '211 - BANCO SISTEMA S.A'],
            ['code' => '212', 'label' => '212 - BANCO ORIGINAL S.A'],
            ['code' => '213', 'label' => '213 - BANCO ARBI S.A'],
            ['code' => '214', 'label' => '214 - BANCO DIBENS S.A'],
            ['code' => '215', 'label' => '215 - BANCO AMERICA DO SUL S.A'],
            ['code' => '216', 'label' => '216 - BANCO REGIONAL MALCON S.A'],
            ['code' => '217', 'label' => '217 - BANCO AGROINVEST S.A'],
            ['code' => '218', 'label' => '218 - BBS - BANCO BONSUCESSO S.A.'],
            ['code' => '219', 'label' => '219 - BANCO DE CREDITO DE SAO PAULO S.A'],
            ['code' => '220', 'label' => '220 - BANCO CREFISUL'],
            ['code' => '221', 'label' => '221 - BANCO GRAPHUS S.A'],
            ['code' => '222', 'label' => '222 - BANCO AGF BRASIL S. A.'],
            ['code' => '223', 'label' => '223 - BANCO INTERUNION S.A'],
            ['code' => '224', 'label' => '224 - BANCO FIBRA S.A'],
            ['code' => '225', 'label' => '225 - BANCO BRASCAN S.A'],
            ['code' => '228', 'label' => '228 - BANCO ICATU S.A'],
            ['code' => '229', 'label' => '229 - BANCO CRUZEIRO S.A'],
            ['code' => '230', 'label' => '230 - BANCO BANDEIRANTES S.A'],
            ['code' => '231', 'label' => '231 - BANCO BOAVISTA S.A'],
            ['code' => '232', 'label' => '232 - BANCO INTERPART S.A'],
            ['code' => '233', 'label' => '233 - BANCO MAPPIN S.A'],
            ['code' => '234', 'label' => '234 - BANCO LAVRA S.A.'],
            ['code' => '235', 'label' => '235 - BANCO LIBERAL S.A'],
            ['code' => '236', 'label' => '236 - BANCO CAMBIAL S.A'],
            ['code' => '237', 'label' => '237 - BANCO BRADESCO S.A'],
            ['code' => '239', 'label' => '239 - BANCO BANCRED S.A'],
            ['code' => '240', 'label' => '240 - BANCO DE CREDITO REAL DE MINAS GERAIS S.'],
            ['code' => '241', 'label' => '241 - BANCO CLASSICO S.A'],
            ['code' => '242', 'label' => '242 - BANCO EUROINVEST S.A'],
            ['code' => '243', 'label' => '243 - BANCO STOCK S.A'],
            ['code' => '244', 'label' => '244 - BANCO CIDADE S.A'],
            ['code' => '245', 'label' => '245 - BANCO EMPRESARIAL S.A'],
            ['code' => '246', 'label' => '246 - BANCO ABC ROMA S.A'],
            ['code' => '247', 'label' => '247 - BANCO OMEGA S.A'],
            ['code' => '249', 'label' => '249 - BANCO INVESTCRED S.A'],
            ['code' => '250', 'label' => '250 - BANCO SCHAHIN CURY S.A'],
            ['code' => '251', 'label' => '251 - BANCO SAO JORGE S.A.'],
            ['code' => '252', 'label' => '252 - BANCO FININVEST S.A'],
            ['code' => '254', 'label' => '254 - BANCO PARANA BANCO S.A'],
            ['code' => '255', 'label' => '255 - MILBANCO S.A.'],
            ['code' => '256', 'label' => '256 - BANCO GULVINVEST S.A'],
            ['code' => '258', 'label' => '258 - BANCO INDUSCRED S.A'],
            ['code' => '260', 'label' => '260 - NU PAGAMENTOS S.A'],
            ['code' => '261', 'label' => '261 - BANCO VARIG S.A'],
            ['code' => '262', 'label' => '262 - BANCO BOREAL S.A'],
            ['code' => '263', 'label' => '263 - BANCO CACIQUE'],
            ['code' => '264', 'label' => '264 - BANCO PERFORMANCE S.A'],
            ['code' => '265', 'label' => '265 - BANCO FATOR S.A'],
            ['code' => '266', 'label' => '266 - BANCO CEDULA S.A'],
            ['code' => '267', 'label' => '267 - BANCO BBM-COM.C.IMOB.CFI S.A.'],
            ['code' => '275', 'label' => '275 - BANCO REAL S.A'],
            ['code' => '277', 'label' => '277 - BANCO PLANIBANC S.A'],
            ['code' => '282', 'label' => '282 - BANCO BRASILEIRO COMERCIAL'],
            ['code' => '291', 'label' => '291 - BANCO DE CREDITO NACIONAL S.A'],
            ['code' => '294', 'label' => '294 - BCR - BANCO DE CREDITO REAL S.A'],
            ['code' => '295', 'label' => '295 - BANCO CREDIPLAN S.A'],
            ['code' => '300', 'label' => '300 - BANCO DE LA NACION ARGENTINA S.A'],
            ['code' => '302', 'label' => '302 - BANCO DO PROGRESSO S.A'],
            ['code' => '303', 'label' => '303 - BANCO HNF S.A.'],
            ['code' => '304', 'label' => '304 - BANCO PONTUAL S.A'],
            ['code' => '308', 'label' => '308 - BANCO COMERCIAL BANCESA S.A.'],
            ['code' => '318', 'label' => '318 - BANCO B.M.G. S.A'],
            ['code' => '320', 'label' => '320 - BANCO INDUSTRIAL E COMERCIAL'],
            ['code' => '341', 'label' => '341 - BANCO ITAU S.A'],
            ['code' => '346', 'label' => '346 - BANCO FRANCES E BRASILEIRO S.A'],
            ['code' => '347', 'label' => '347 - BANCO SUDAMERIS BRASIL S.A'],
            ['code' => '351', 'label' => '351 - BANCO BOZANO SIMONSEN S.A'],
            ['code' => '353', 'label' => '353 - BANCO GERAL DO COMERCIO S.A'],
            ['code' => '356', 'label' => '356 - ABN AMRO S.A'],
            ['code' => '366', 'label' => '366 - BANCO SOGERAL S.A'],
            ['code' => '369', 'label' => '369 - PONTUAL'],
            ['code' => '370', 'label' => '370 - BEAL - BANCO EUROPEU PARA AMERICA LATINA'],
            ['code' => '372', 'label' => '372 - BANCO ITAMARATI S.A'],
            ['code' => '375', 'label' => '375 - BANCO FENICIA S.A'],
            ['code' => '376', 'label' => '376 - CHASE MANHATTAN BANK S.A'],
            ['code' => '388', 'label' => '388 - BANCO MERCANTIL DE DESCONTOS S/A'],
            ['code' => '389', 'label' => '389 - BANCO MERCANTIL DO BRASIL S.A'],
            ['code' => '392', 'label' => '392 - BANCO MERCANTIL DE SAO PAULO S.A'],
            ['code' => '394', 'label' => '394 - BANCO B.M.C. S.A'],
            ['code' => '399', 'label' => '399 - HSBC BANK BRASIL S.A. – BANCO MÚLTIPLO'],
            ['code' => '409', 'label' => '409 - UNIBANCO - UNIAO DOS BANCOS BRASILEIROS'],
            ['code' => '412', 'label' => '412 - BANCO NACIONAL DA BAHIA S.A'],
            ['code' => '415', 'label' => '415 - BANCO NACIONAL S.A'],
            ['code' => '420', 'label' => '420 - BANCO NACIONAL DO NORTE S.A'],
            ['code' => '422', 'label' => '422 - BANCO SAFRA S.A'],
            ['code' => '424', 'label' => '424 - BANCO NOROESTE S.A'],
            ['code' => '434', 'label' => '434 - BANCO FORTALEZA S.A'],
            ['code' => '453', 'label' => '453 - BANCO RURAL S.A'],
            ['code' => '456', 'label' => '456 - BANCO TOKIO S.A'],
            ['code' => '464', 'label' => '464 - BANCO SUMITOMO BRASILEIRO S.A'],
            ['code' => '466', 'label' => '466 - BANCO MITSUBISHI BRASILEIRO S.A'],
            ['code' => '472', 'label' => '472 - LLOYDS BANK PLC'],
            ['code' => '473', 'label' => '473 - BANCO FINANCIAL PORTUGUES S.A'],
            ['code' => '477', 'label' => '477 - CITIBANK N.A'],
            ['code' => '479', 'label' => '479 - BANCO DE BOSTON S.A'],
            ['code' => '480', 'label' => '480 - BANCO PORTUGUES DO ATLANTICO-BRASIL S.A'],
            ['code' => '483', 'label' => '483 - BANCO AGRIMISA S.A.'],
            ['code' => '487', 'label' => '487 - DEUTSCHE BANK S.A - BANCO ALEMAO'],
            ['code' => '488', 'label' => '488 - BANCO J. P. MORGAN S.A'],
            ['code' => '489', 'label' => '489 - BANESTO BANCO URUGAUAY S.A'],
            ['code' => '492', 'label' => '492 - INTERNATIONALE NEDERLANDEN BANK N.V.'],
            ['code' => '493', 'label' => '493 - BANCO UNION S.A.C.A'],
            ['code' => '494', 'label' => '494 - BANCO LA REP. ORIENTAL DEL URUGUAY'],
            ['code' => '495', 'label' => '495 - BANCO LA PROVINCIA DE BUENOS AIRES'],
            ['code' => '496', 'label' => '496 - BANCO EXTERIOR DE ESPANA S.A'],
            ['code' => '498', 'label' => '498 - CENTRO HISPANO BANCO'],
            ['code' => '499', 'label' => '499 - BANCO IOCHPE S.A'],
            ['code' => '501', 'label' => '501 - BANCO BRASILEIRO IRAQUIANO S.A.'],
            ['code' => '502', 'label' => '502 - BANCO SANTANDER S.A'],
            ['code' => '504', 'label' => '504 - BANCO MULTIPLIC S.A'],
            ['code' => '505', 'label' => '505 - BANCO GARANTIA S.A'],
            ['code' => '600', 'label' => '600 - BANCO LUSO BRASILEIRO S.A'],
            ['code' => '601', 'label' => '601 - BFC BANCO S.A.'],
            ['code' => '602', 'label' => '602 - BANCO PATENTE S.A'],
            ['code' => '604', 'label' => '604 - BANCO INDUSTRIAL DO BRASIL S.A'],
            ['code' => '607', 'label' => '607 - BANCO SANTOS NEVES S.A'],
            ['code' => '608', 'label' => '608 - BANCO OPEN S.A'],
            ['code' => '610', 'label' => '610 - BANCO V.R. S.A'],
            ['code' => '611', 'label' => '611 - BANCO PAULISTA S.A'],
            ['code' => '612', 'label' => '612 - BANCO GUANABARA S.A'],
            ['code' => '613', 'label' => '613 - BANCO PECUNIA S.A'],
            ['code' => '616', 'label' => '616 - BANCO INTERPACIFICO S.A'],
            ['code' => '617', 'label' => '617 - BANCO INVESTOR S.A.'],
            ['code' => '618', 'label' => '618 - BANCO TENDENCIA S.A'],
            ['code' => '621', 'label' => '621 - BANCO APLICAP S.A.'],
            ['code' => '622', 'label' => '622 - BANCO DRACMA S.A'],
            ['code' => '623', 'label' => '623 - BANCO PANAMERICANO S.A'],
            ['code' => '624', 'label' => '624 - BANCO GENERAL MOTORS S.A'],
            ['code' => '625', 'label' => '625 - BANCO ARAUCARIA S.A'],
            ['code' => '626', 'label' => '626 - BANCO FICSA S.A'],
            ['code' => '627', 'label' => '627 - BANCO DESTAK S.A'],
            ['code' => '628', 'label' => '628 - BANCO CRITERIUM S.A'],
            ['code' => '629', 'label' => '629 - BANCORP BANCO COML. E. DE INVESTMENTO'],
            ['code' => '630', 'label' => '630 - BANCO INTERCAP S.A'],
            ['code' => '633', 'label' => '633 - BANCO REDIMENTO S.A'],
            ['code' => '634', 'label' => '634 - BANCO TRIANGULO S.A'],
            ['code' => '635', 'label' => '635 - BANCO DO ESTADO DO AMAPA S.A'],
            ['code' => '637', 'label' => '637 - BANCO SOFISA S.A'],
            ['code' => '638', 'label' => '638 - BANCO PROSPER S.A'],
            ['code' => '639', 'label' => '639 - BIG S.A. - BANCO IRMAOS GUIMARAES'],
            ['code' => '640', 'label' => '640 - BANCO DE CREDITO METROPOLITANO S.A'],
            ['code' => '641', 'label' => '641 - BANCO EXCEL ECONOMICO S/A'],
            ['code' => '643', 'label' => '643 - BANCO SEGMENTO S.A'],
            ['code' => '645', 'label' => '645 - BANCO DO ESTADO DE RORAIMA S.A'],
            ['code' => '647', 'label' => '647 - BANCO MARKA S.A'],
            ['code' => '648', 'label' => '648 - BANCO ATLANTIS S.A'],
            ['code' => '649', 'label' => '649 - BANCO DIMENSAO S.A'],
            ['code' => '650', 'label' => '650 - BANCO PEBB S.A'],
            ['code' => '652', 'label' => '652 - ITAÚ UNIBANCO HOLDING S.A.'],
            ['code' => '653', 'label' => '653 - BANCO INDUSVAL S.A'],
            ['code' => '654', 'label' => '654 - BANCO A. J. RENNER S.A'],
            ['code' => '655', 'label' => '655 - BANCO VOTORANTIM S.A.'],
            ['code' => '656', 'label' => '656 - BANCO MATRIX S.A'],
            ['code' => '657', 'label' => '657 - BANCO TECNICORP S.A'],
            ['code' => '658', 'label' => '658 - BANCO PORTO REAL S.A'],
            ['code' => '702', 'label' => '702 - BANCO SANTOS S.A'],
            ['code' => '705', 'label' => '705 - BANCO INVESTCORP S.A.'],
            ['code' => '707', 'label' => '707 - BANCO DAYCOVAL S.A'],
            ['code' => '711', 'label' => '711 - BANCO VETOR S.A.'],
            ['code' => '713', 'label' => '713 - BANCO CINDAM S.A'],
            ['code' => '715', 'label' => '715 - BANCO VEGA S.A'],
            ['code' => '718', 'label' => '718 - BANCO OPERADOR S.A'],
            ['code' => '719', 'label' => '719 - BANCO PRIMUS S.A'],
            ['code' => '720', 'label' => '720 - BANCO MAXINVEST S.A'],
            ['code' => '721', 'label' => '721 - BANCO CREDIBEL S.A'],
            ['code' => '722', 'label' => '722 - BANCO INTERIOR DE SAO PAULO S.A'],
            ['code' => '724', 'label' => '724 - BANCO PORTO SEGURO S.A'],
            ['code' => '725', 'label' => '725 - BANCO FINABANCO S.A'],
            ['code' => '726', 'label' => '726 - BANCO UNIVERSAL S.A'],
            ['code' => '728', 'label' => '728 - BANCO FITAL S.A'],
            ['code' => '729', 'label' => '729 - BANCO FONTE S.A'],
            ['code' => '730', 'label' => '730 - BANCO COMERCIAL PARAGUAYO S.A'],
            ['code' => '731', 'label' => '731 - BANCO GNPP S.A.'],
            ['code' => '732', 'label' => '732 - BANCO PREMIER S.A.'],
            ['code' => '733', 'label' => '733 - BANCO NACOES S.A.'],
            ['code' => '734', 'label' => '734 - BANCO GERDAU S.A'],
            ['code' => '735', 'label' => '735 - BACO POTENCIAL'],
            ['code' => '736', 'label' => '736 - BANCO UNITED S.A'],
            ['code' => '737', 'label' => '737 - THECA'],
            ['code' => '738', 'label' => '738 - MARADA'],
            ['code' => '739', 'label' => '739 - BGN'],
            ['code' => '740', 'label' => '740 - BCN BARCLAYS'],
            ['code' => '741', 'label' => '741 - BRP'],
            ['code' => '742', 'label' => '742 - EQUATORIAL'],
            ['code' => '743', 'label' => '743 - BANCO EMBLEMA S.A'],
            ['code' => '744', 'label' => '744 - THE FIRST NATIONAL BANK OF BOSTON'],
            ['code' => '745', 'label' => '745 - CITIBAN N.A.'],
            ['code' => '746', 'label' => '746 - MODAL S\A'],
            ['code' => '747', 'label' => '747 - RAIBOBANK DO BRASIL'],
            ['code' => '748', 'label' => '748 - SICREDI'],
            ['code' => '749', 'label' => '749 - BRMSANTIL SA'],
            ['code' => '750', 'label' => '750 - BANCO REPUBLIC NATIONAL OF NEW YORK (BRA'],
            ['code' => '751', 'label' => '751 - DRESDNER BANK LATEINAMERIKA-BRASIL S/A'],
            ['code' => '752', 'label' => '752 - BANCO BANQUE NATIONALE DE PARIS BRASIL S'],
            ['code' => '753', 'label' => '753 - BANCO COMERCIAL URUGUAI S.A.'],
            ['code' => '755', 'label' => '755 - BANCO MERRILL LYNCH S.A'],
            ['code' => '756', 'label' => '756 - BANCO COOPERATIVO DO BRASIL S.A.'],
            ['code' => '757', 'label' => '757 - BANCO KEB DO BRASIL S.A.'],
        ];

        foreach($banks as $bank) {
            $new = new ModelsBank();
            $new->code = $bank['code'];
            $new->label = $bank['label'];
            $new->save();
        }
    }
}
